import {test} from "node:test";import assert from "node:assert/strict";import {DatabaseSync} from "node:sqlite";import {readFileSync} from "node:fs";import {leadSchema,imageType} from "../lib/validation";import {createLead} from "../lib/intake";import {captureMode} from "../lib/config";import {requireOrigin,authorize,boundedBody,rateLimit} from "../lib/http";import {listCrmLeads,mapCrmLead} from "../lib/crm-data";
const input={problem:"fossa",location:"Área externa fictícia",property:"residencia",urgency:"planejar",access:"Acesso de teste",region:"Região de teste",cep:"",name:"Teste Limpax",phone:"11999999999",email:"teste@example.com",notes:"Dados sintéticos",marketing:false,privacy:true,reviewAcknowledged:true,website:""};
function db(){const sql=new DatabaseSync(":memory:");sql.exec("PRAGMA foreign_keys=ON");for(const migration of ["drizzle/0000_fat_supernaut.sql","drizzle/0001_panoramic_tarot.sql","drizzle/0002_burly_blue_shield.sql"])sql.exec(readFileSync(migration,"utf8"));const wrapper={prepare(query:string){let values:unknown[]=[];const stmt={bind(...v:unknown[]){values=v;return stmt},async first(){return sql.prepare(query).get(...values as any[])??null},async all(){return {results:sql.prepare(query).all(...values as any[])}},async run(){return sql.prepare(query).run(...values as any[])}};return stmt},async batch(statements:any[]){sql.exec("BEGIN");try{const r=[];for(const st of statements)r.push(await st.run());sql.exec("COMMIT");return r}catch(e){sql.exec("ROLLBACK");throw e}}};return {sql,DB:wrapper as unknown as D1Database}}
test("strict validation rejects unknown fields, invalid phones and missing privacy",()=>{assert(leadSchema.safeParse(input).success);for(const bad of [{...input,phone:"12"},{...input,privacy:false},{...input,admin:true},{...input,website:"spam"},{...input,notes:"x".repeat(1201)}])assert.equal(leadSchema.safeParse(bad).success,false)});
test("lead and outbox persist atomically; exact retry returns same id; changed retry conflicts",async()=>{const {sql,DB}=db();const key=crypto.randomUUID();const one=await createLead(input,key,{DB});const two=await createLead(input,key,{DB});assert.equal(one.id,two.id);assert.equal(two.replayed,true);assert.equal(sql.prepare("SELECT count(*) n FROM leads").get()!.n,1);assert.equal(sql.prepare("SELECT state FROM outbox").get()!.state,"review");await assert.rejects(createLead({...input,name:"Changed"},key,{DB}),{status:409});await assert.rejects(createLead({...input,reviewAcknowledged:false},crypto.randomUUID(),{DB}),{status:400});sql.close()});
test("outbox failure rolls back lead",async()=>{const {sql,DB}=db();sql.exec("DROP TABLE outbox");await assert.rejects(createLead(input,crypto.randomUUID(),{DB}));assert.equal(sql.prepare("SELECT count(*) n FROM leads").get()!.n,0);sql.close()});
test("live capture requires complete operational configuration",()=>{assert.equal(captureMode({CAPTURE_MODE:"live"}),"review");assert.equal(captureMode({CAPTURE_MODE:"disabled"}),"disabled");assert.equal(captureMode({CAPTURE_MODE:"live",LEGAL_NAME:"Test",PRIVACY_CONTACT:"test@example.com",RETENTION_DAYS:"90",RATE_LIMIT_SECRET:"x".repeat(32)}),"live")});
test("cross origin and unauthenticated CRM fail closed",async()=>{assert.throws(()=>requireOrigin(new Request("https://limpax-fluindo.italopablo.chatgpt.site/api/check",{headers:{origin:"https://evil.example"}}),{}),{status:403});await assert.rejects(authorize(new Request("https://test"),{}),{status:503});await assert.rejects(authorize(new Request("https://test"),{CRM_API_TOKEN:"x".repeat(32)}),{status:401});await authorize(new Request("https://test",{headers:{Authorization:"Bearer "+"x".repeat(32)}}),{CRM_API_TOKEN:"x".repeat(32)})});
test("stream body limit works without content-length",async()=>{await assert.rejects(boundedBody(new Request("https://test",{method:"POST",body:"x".repeat(100)}),20),{status:413})});
test("rate limit is persistent and bounded",async()=>{const {DB,sql}=db();const r=new Request("https://test");await rateLimit(r,{DB},"test",1);await assert.rejects(rateLimit(r,{DB},"test",1),{status:429});sql.close()});
test("file signatures reject HTML and SVG",()=>{assert.equal(imageType(new TextEncoder().encode("<svg>bad</svg>")),null);assert.equal(imageType(new Uint8Array([255,216,255,0])),"image/jpeg")});
test("CRM list maps the public contract, filters and paginates with global totals",async()=>{const {DB,sql}=db();for(let i=0;i<12;i++)await createLead({...input,name:"Cliente "+i,region:i%2?"Norte":"Sul"},crypto.randomUUID(),{DB});sql.exec("UPDATE leads SET status='qualificado' WHERE seq<=3");const first=await listCrmLeads(DB,{page:1,pageSize:10});assert.equal(first.total,12);assert.equal(first.leads.length,10);assert.equal(first.pages,2);assert.equal(first.totals.qualificado,3);assert.equal(first.leads[0].contact.name.startsWith("Cliente"),true);const filtered=await listCrmLeads(DB,{search:"Norte",pageSize:10});assert.equal(filtered.total,6);assert.equal(filtered.totals.qualificado,3);assert.deepEqual(Object.keys(mapCrmLead(sql.prepare("SELECT * FROM leads LIMIT 1").get()!)).includes("assignedTo"),true);sql.close()});
test("CRM failure preserves lead and schedules retry; success marks delivered",async()=>{const {sql,DB}=db();const {env}=await import("./cloudflare-mock");const {POST}=await import("../app/api/crm/dispatch/route");const s={DB,CAPTURE_MODE:"live",LEGAL_NAME:"Fictícia",PRIVACY_CONTACT:"test@example.com",RETENTION_DAYS:"90",RATE_LIMIT_SECRET:"s".repeat(32),CRM_API_TOKEN:"t".repeat(32),CRM_WEBHOOK_URL:"https://crm.example.test/webhook",CRM_WEBHOOK_SECRET:"private-test-secret"};Object.assign(env,s);const lead=await createLead(input,crypto.randomUUID(),s);const previous=globalThis.fetch;const req=()=>new Request("https://test/api/crm/dispatch",{method:"POST",headers:{authorization:"Bearer "+s.CRM_API_TOKEN}});try{globalThis.fetch=async()=>new Response("no",{status:500});assert.equal((await POST(req())).status,200);assert.equal(sql.prepare("SELECT state FROM outbox").get()!.state,"pending");assert.equal(sql.prepare("SELECT count(*) n FROM leads").get()!.n,1);sql.exec("UPDATE outbox SET next_attempt=0");globalThis.fetch=async(_url,options)=>{assert.equal(new Headers(options?.headers).get("Idempotency-Key"),lead.id);return new Response("ok")};assert.equal((await POST(req())).status,200);assert.equal(sql.prepare("SELECT state FROM outbox").get()!.state,"delivered")}finally{globalThis.fetch=previous;for(const k of Object.keys(env))delete env[k];sql.close()}});
test("erase cascades contacts, uploads and outbox while preserving unlinked service history",async()=>{const {sql,DB}=db();const l=await createLead(input,crypto.randomUUID(),{DB});sql.prepare("INSERT INTO attachments VALUES (?,?,?,?,?,?)").run("file",l.id,"key","image/jpeg",40,Date.now());sql.prepare("INSERT INTO service_records(id,lead_id) VALUES(?,?)").run("service",l.id);sql.prepare("DELETE FROM leads WHERE id=?").run(l.id);assert.equal(sql.prepare("SELECT count(*) n FROM attachments").get()!.n,0);assert.equal(sql.prepare("SELECT count(*) n FROM outbox").get()!.n,0);assert.equal(sql.prepare("SELECT lead_id FROM service_records").get()!.lead_id,null);sql.close()});

