import {requireCrmMutation,requireCrmAdmin} from "@/lib/crm";
import {cleanOptional,digits} from "@/lib/crm-customers";
import {database,failure,json,readJson,ApiError} from "@/lib/http";
import {settings} from "@/lib/config";
import {uuidSchema} from "@/lib/validation";
import {z} from "zod";
type ContactRow={name:string;role:string|null;phone:string|null;phone_normalized:string|null;email:string|null;is_primary:number};

const updateSchema=z.object({name:z.string().trim().min(2).max(180).optional(),role:z.string().max(100).nullable().optional(),phone:z.string().max(30).nullable().optional(),email:z.string().email().max(200).or(z.literal("")).nullable().optional(),primary:z.boolean().optional()}).strict();

export async function PATCH(req:Request,{params}:{params:Promise<{id:string;contactId:string}>}){try{const actor=await requireCrmMutation(req);const {id,contactId}=await params;if(!uuidSchema.safeParse(id).success||!uuidSchema.safeParse(contactId).success)throw new ApiError(400,"Identificador inválido.");const parsed=updateSchema.safeParse(await readJson(req));if(!parsed.success||!Object.keys(parsed.data).length)throw new ApiError(400,"Atualização inválida.");const data=parsed.data,db=database(settings());const current=await db.prepare("SELECT * FROM customer_contacts WHERE id=? AND customer_id=?").bind(contactId,id).first<ContactRow>();if(!current)throw new ApiError(404,"Contato não encontrado.");const now=Date.now(),statements=[];if(data.primary)statements.push(db.prepare("UPDATE customer_contacts SET is_primary=0,updated_at=? WHERE customer_id=?").bind(now,id));statements.push(db.prepare("UPDATE customer_contacts SET name=?,role=?,phone=?,phone_normalized=?,email=?,is_primary=?,updated_at=? WHERE id=?").bind(data.name??current.name,data.role===undefined?current.role:cleanOptional(data.role),data.phone===undefined?current.phone:cleanOptional(data.phone),data.phone===undefined?current.phone_normalized:digits(data.phone),data.email===undefined?current.email:(cleanOptional(data.email)?.toLowerCase()||null),data.primary===undefined?current.is_primary:(data.primary?1:0),now,contactId),db.prepare("UPDATE customers SET updated_at=? WHERE id=?").bind(now,id),db.prepare("INSERT INTO crm_audit_log VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),"customer",id,"contact_updated",actor.email,JSON.stringify({contactId,...data}),now));await db.batch(statements);return json({updatedAt:now})}catch(e){return failure(e)}}

export async function DELETE(req:Request,{params}:{params:Promise<{id:string;contactId:string}>}){try{const actor=await requireCrmAdmin(req);const {id,contactId}=await params;if(!uuidSchema.safeParse(id).success||!uuidSchema.safeParse(contactId).success)throw new ApiError(400,"Identificador inválido.");const db=database(settings()),current=await db.prepare("SELECT id FROM customer_contacts WHERE id=? AND customer_id=?").bind(contactId,id).first();if(!current)throw new ApiError(404,"Contato não encontrado.");const now=Date.now();await db.batch([db.prepare("DELETE FROM customer_contacts WHERE id=?").bind(contactId),db.prepare("UPDATE customers SET updated_at=? WHERE id=?").bind(now,id),db.prepare("INSERT INTO crm_audit_log VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),"customer",id,"contact_deleted",actor.email,JSON.stringify({contactId}),now)]);return json({deleted:true})}catch(e){return failure(e)}}
