import Image from "next/image";
import Link from "next/link";
import {SiteHeader} from "@/components/site-header";
import {QuickDiagnosis} from "@/components/quick-diagnosis";
import {SiteFooter} from "@/components/site-footer";
import {FlowMotion} from "@/components/flow-motion";
import {Consent} from "@/components/consent";
import {services} from "@/lib/content";
export default function Home(){return <><SiteHeader/><FlowMotion/><main id="conteudo"><section className="hero"><Image className="hero-image" src="/media/hero.webp" alt="Ilustração conceitual por IA de caminhão, sem representar a frota real da Limpax" width={1536} height={1024} priority/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow yellow">LIMPAX / DISTRITO FEDERAL</p><h1>Tudo precisa<br/>continuar<br/><em>fluindo.</em></h1><p className="hero-copy">Desde 2005, uma história<br/>construída em operação.</p><div className="actions"><a href="#diagnostico" className="button">Preciso resolver ↗</a><a className="text-link" href="#operacao">Conhecer a operação ↓</a></div></div><aside className="operational-glass"><p className="eyebrow">OPERAÇÃO / DF</p><dl><div><dt>Frota</dt><dd>03</dd></div><div><dt>Desde</dt><dd>2005</dd></div></dl></aside><div className="hero-base"><span>01 / EM MOVIMENTO</span><span>Imagem conceitual / IA</span><a href="#diagnostico">ROLE PARA EXPLORAR ↓</a></div></section><QuickDiagnosis/>
<section className="operation" id="operacao"><div className="operation-photo"><Image src="/media/operation.webp" alt="Ilustração por IA de mangueira e conexão de equipamento; imagem provisória" width={1536} height={1024} loading="lazy"/><span className="image-caption">IMAGEM CONCEITUAL / IA</span></div><div className="operation-copy"><p className="eyebrow yellow">03 / OPERAÇÃO</p><h2>Chamou.<br/>A Limpax<br/>entra em ação.</h2><p>Mais do que executar um serviço, existe uma operação para colocar tudo de volta em funcionamento.</p><ol className="operation-steps">{["Chamado","Entendimento","Orçamento","Execução","Conclusão"].map((v,i)=><li key={v}><span>0{i+1}</span>{v}</li>)}</ol><p className="fine-print">Processo proposto [VALIDAR com a Limpax].</p></div></section>
<section className="services section concrete" id="servicos"><div className="services-heading"><p className="eyebrow">04 / SERVIÇOS</p><h2>O problema muda.<br/>A operação certa<br/>também.</h2><p>Portfólio provisório. Disponibilidade e escopo de cada serviço [VALIDAR].</p><nav aria-label="Capítulos de serviços">{services.map(s=><a href={"#"+s.slug} key={s.id}><span>{s.id}</span>{s.label}</a>)}</nav></div><div className="service-chapters">{services.map(s=><article className="service-chapter" id={s.slug} key={s.slug}><p className="eyebrow">{s.id} / {s.label}</p><div className="chapter-number" aria-hidden="true">{s.id}</div><h3>{s.title}</h3><p>{s.copy}</p><span className="validation-label">DISPONIBILIDADE [VALIDAR]</span><Link className="text-link" href={"/servicos/"+s.slug}>Conhecer este capítulo ↗</Link></article>)}</div></section>
<section className="section fleet" id="frota"><div className="fleet-heading"><span className="fleet-number">03</span><div><p className="eyebrow yellow">05 / FROTA</p><h2>Três caminhões.<br/>Uma operação<br/>em movimento.</h2></div></div><div className="fleet-visual"><Image src="/media/hero.webp" alt="Visual conceitual de caminhão. A aparência da frota real ainda será documentada." width={1536} height={1024} loading="lazy"/><div className="fleet-tags">{["01","02","03"].map(id=><div key={id}><span className="eyebrow">FROTA / LIMPAX</span><strong>LXP / {id}</strong></div>)}</div><span className="image-caption">CONCEITO VISUAL / IA · IDENTIFICADORES EDITORIAIS</span></div><p className="fleet-note">Capacidades, equipamentos e funções de cada veículo [VALIDAR].</p></section>
<section className="section business" id="empresas"><p className="eyebrow">06 / CADA CENÁRIO, UM CAMINHO</p><div className="journeys"><div><span className="eyebrow">RESIDÊNCIAS / DEMANDAS PONTUAIS</span><h2>Preciso<br/>resolver.</h2><p>Conte o problema e prepare as informações para a equipe.</p><Link href="/check?imovel=residencia" className="button">Preparar atendimento ↗</Link></div><div><span className="eyebrow">EMPRESAS / CONDOMÍNIOS</span><h2>Sua operação<br/>não pode parar.</h2><p>Informe o contexto do imóvel, o acesso e a necessidade da sua operação.</p><Link href="/check?imovel=empresa" className="button">Preparar demanda empresarial ↗</Link><p className="fine-print">Contratos, recorrência e condições de atendimento [VALIDAR].</p></div></div></section>
<section className="section concrete about" id="sobre"><div><p className="eyebrow">07 / HISTÓRIA E TERRITÓRIO</p><span className="year">2005</span><div className="history-line" aria-hidden="true"/><h2>Mais de duas décadas.<br/>Distrito Federal.</h2></div><div className="territory"><span className="territory-mark" aria-hidden="true">DF</span><p>Uma história construída no Distrito Federal. Três caminhões fazem parte da operação Limpax.</p><p>Informe sua região no Check para consultar a possibilidade de atendimento. Cobertura por localidade [VALIDAR].</p><Link className="text-link" href="/check">Informar minha região ↗</Link></div></section>
<section className="section check-intro"><div><p className="eyebrow yellow">08 / LIMPAX CHECK</p><h2>Mostre o problema.<br/>Prepare o<br/>próximo passo.</h2><p className="body-copy">Algumas perguntas para organizar seu cenário. Sem adivinhar o serviço, o preço ou o prazo.</p><Link href="/check" className="button">Começar Limpax Check ↗</Link></div><ol className="check-preview">{["Problema","Local","Tipo de imóvel","Urgência","Acesso","Fotos opcionais","Região","Contato"].map((t,i)=><li key={t}><span>0{i+1}</span>{t}<span aria-hidden="true">→</span></li>)}</ol></section>
<section className="section recurrence"><p className="eyebrow">09 / PRÓXIMO CAPÍTULO</p><h2>Resolver é importante.<br/>Evitar é melhor.</h2><p>Histórico, acompanhamento e manutenção preventiva fazem parte da visão de continuidade da marca.</p><span className="validation-label">MODELO FUTURO [VALIDAR] · AINDA NÃO DISPONÍVEL</span></section>
<section className="section final-cta"><p className="eyebrow yellow">10 / VAMOS CONTINUAR</p><h2>Precisa<br/><em>resolver?</em></h2><Link href="/check" className="button">Preparar minha solicitação ↗</Link><div className="closing-line" aria-hidden="true"/></section></main><SiteFooter/><Consent/></>}
