"use client";
import {useEffect,useRef,useState} from "react";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {Checkbox} from "@/components/ui/checkbox";
import {Progress} from "@/components/ui/progress";
import {problems} from "@/lib/content";
import {leadSchema,type LeadInput} from "@/lib/validation";
import {track} from "@/components/consent";
const labels=["Qual é o problema?","Onde acontece?","Que tipo de imóvel?","Qual é a urgência?","Como é o acesso?","Quer adicionar fotos?","Em qual região?","Como podemos falar com você?"];
const initial:LeadInput={problem:"outro",location:"",property:"residencia",urgency:"nao-sei",access:"",region:"",cep:"",name:"",phone:"",email:"",notes:"",marketing:false,privacy:true,reviewAcknowledged:false,website:""};
type Result={id:string;mode:string;uploadToken?:string;replayed?:boolean};
function Choices({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:readonly (readonly [string,string])[];label:string}){return <RadioGroup value={value} onValueChange={onChange} aria-label={label} className="check-choices">{options.map(([id,text])=><label className={"option "+(value===id?"selected":"")} key={id}><RadioGroupItem value={id}/><span>{text}</span></label>)}</RadioGroup>}
async function cleanPhoto(file:File){const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext("2d");if(!ctx){bitmap.close();throw new Error("Não foi possível preparar a foto.")}ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error("Não foi possível preparar a foto.")),"image/jpeg",.82))}
export function CheckForm({mode}:{mode:string}){const [step,setStep]=useState(0);const [data,setData]=useState<LeadInput>(initial);const [privacy,setPrivacy]=useState(false);const [photos,setPhotos]=useState<File[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [result,setResult]=useState<Result|null>(null);const [photoStatus,setPhotoStatus]=useState("");const [uploaded,setUploaded]=useState(0);const key=useRef("");const heading=useRef<HTMLHeadingElement>(null);const focusNeeded=useRef(false);
function update<K extends keyof LeadInput>(field:K,value:LeadInput[K]){setData(d=>({...d,[field]:value}));setError("")}
useEffect(()=>{key.current=crypto.randomUUID();const params=new URLSearchParams(location.search);const problem=params.get("problema");const property=params.get("imovel");setData(d=>({...d,...(problems.some(([p])=>p===problem)?{problem:problem as LeadInput["problem"]}:{}),...(property==="empresa"||property==="condominio"?{property}: {})}));track("check_started");
const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:"stage_limpax_problem",title:"Preparar problema no Limpax Check",description:"Seleciona a categoria visível e abre o primeiro passo, sem enviar dados.",inputSchema:{type:"object",properties:{problem:{type:"string",enum:problems.map(([p])=>p)}},required:["problem"],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const v=input as {problem?:string};if(!v||Object.keys(v).length!==1||!problems.some(([p])=>p===v.problem))throw new Error("Categoria inválida");setData(d=>({...d,problem:v.problem as LeadInput["problem"]}));setStep(0);return new Promise(resolve=>requestAnimationFrame(()=>resolve({staged:true,step:1}))) }},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
useEffect(()=>{if(focusNeeded.current)heading.current?.focus()},[step,result]);
function go(next:number){focusNeeded.current=true;setStep(next);setError("")}
function next(){const required:Record<number,[keyof LeadInput,number]>={1:["location",2],4:["access",2],6:["region",2]};const rule=required[step];if(rule&&String(data[rule[0]]).trim().length<rule[1]){setError("Preencha o campo para continuar.");return}if(step===6&&data.cep&&!/^[0-9]{8}$/.test(data.cep)){setError("Informe um CEP com 8 números ou deixe em branco.");return}go(Math.min(7,step+1))}
async function uploadPhotos(r:Result,start=0){if(!photos.length)return;if(!r.uploadToken){setPhotoStatus("Solicitação registrada. As fotos não foram anexadas; o prazo de envio pode ter terminado.");return}setPhotoStatus("Preparando fotos…");for(let i=start;i<photos.length;i++){try{const image=await cleanPhoto(photos[i]);const response=await fetch("/api/uploads",{method:"POST",headers:{"Content-Type":"image/jpeg","X-Lead-Id":r.id,"X-Upload-Token":r.uploadToken},body:image});const body=await response.json() as Result & {error?:string};if(!response.ok)throw new Error(body.error||"Falha ao anexar foto.");setUploaded(i+1)}catch(e){setPhotoStatus((e as Error).message+" Sua solicitação já está registrada.");return}}setPhotoStatus("Fotos anexadas com segurança.")}
async function submit(){if(busy||result)return;setError("");const parsed=leadSchema.safeParse({...data,privacy});if(!parsed.success){setError("Revise nome, telefone, email e a ciência do aviso de privacidade.");return}if(mode==="review"&&!data.reviewAcknowledged){setError("Confirme que está usando dados fictícios.");return}setBusy(true);try{const response=await fetch("/api/check",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key.current},body:JSON.stringify(parsed.data)});const body=await response.json() as Result & {error?:string};if(!response.ok)throw new Error(body.error||"Não foi possível registrar.");focusNeeded.current=true;setResult(body);track("check_completed");await uploadPhotos(body)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
return <div className="check-shell"><div className="check-meta"><span>LIMPAX / CHECK</span><span>{result?"CONCLUÍDO":String(step+1).padStart(2,"0")+" / 08"}</span></div><Progress value={result?100:(step+1)*12.5} aria-label="Progresso do Limpax Check" className="check-progress"/>{mode==="review"&&<p className="review-notice">AMBIENTE DE REVISÃO · Use apenas dados fictícios. Nenhum chamado será encaminhado para atendimento.</p>}{mode==="disabled"&&<p className="review-notice">Recebimento indisponível no momento. Você pode preparar as respostas e tentar novamente mais tarde.</p>}{result?<div className="success"><p className="eyebrow">✓ INFORMAÇÕES REGISTRADAS</p><h1 ref={heading} tabIndex={-1}>{result.mode==="review"?"Teste registrado.":"Solicitação registrada."}</h1><p>{result.mode==="review"?"Este registro é de revisão. Nenhum atendimento foi solicitado.":"Guarde o protocolo. O registro não confirma agendamento ou prazo de atendimento."}</p><p className="protocol">Protocolo: <strong>{result.id}</strong></p><p role="status">{photoStatus}</p>{photos.length>uploaded&&result.uploadToken&&<button className="outline-button" disabled={busy} onClick={async()=>{setBusy(true);await uploadPhotos(result,uploaded);setBusy(false)}}>Tentar anexar fotos novamente</button>}<a href="/" className="button">Voltar para a Limpax ↗</a></div>:<form onSubmit={e=>{e.preventDefault();if(step<7)next();else void submit()}} noValidate><h1 ref={heading} tabIndex={-1}>{labels[step]}</h1><p className="step-description">{["Escolha o que mais se aproxima do cenário.","Exemplo: banheiro, cozinha ou área externa.","Isso ajuda a organizar sua solicitação.","A urgência informada não confirma disponibilidade ou prazo.","Informe restrições, portão, escadas ou o que souber sobre o acesso.","Até 3 fotos, com no máximo 4 MB cada. Não inclua pessoas ou documentos.","Informe a região ou cidade. A equipe confirma a possibilidade de atendimento.","Revise suas respostas antes de enviar."][step]}</p><div className="step-content">
{step===0&&<Choices value={data.problem} onChange={v=>update("problem",v as LeadInput["problem"])} options={problems} label="Problema"/>}
{step===1&&<label className="field">Local do problema<input required maxLength={160} value={data.location} onChange={e=>update("location",e.target.value)} aria-describedby="check-error" aria-invalid={!!error}/></label>}
{step===2&&<Choices value={data.property} onChange={v=>update("property",v as LeadInput["property"])} options={[["residencia","Residência"],["condominio","Condomínio"],["empresa","Empresa"]]} label="Tipo de imóvel"/>}
{step===3&&<Choices value={data.urgency} onChange={v=>update("urgency",v as LeadInput["urgency"])} options={[["agora","Está afetando o funcionamento agora"],["planejar","Quero planejar um atendimento"],["nao-sei","Ainda não sei"]]} label="Urgência"/>}
{step===4&&<label className="field">Acesso ao local<textarea required maxLength={500} rows={4} value={data.access} onChange={e=>update("access",e.target.value)} aria-describedby="check-error" aria-invalid={!!error}/></label>}
{step===5&&<><label className="upload-zone">Adicionar fotos (opcional)<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{const selected=Array.from(e.target.files||[]);if(selected.length>3||selected.some(f=>f.size>4*1024*1024||!["image/jpeg","image/png","image/webp"].includes(f.type))){setError("Selecione até 3 imagens JPEG, PNG ou WebP, de no máximo 4 MB cada.");e.target.value="";return}setPhotos(selected);setError("")}}/></label><p>{photos.length} foto(s) selecionada(s).</p>{photos.length>0&&<button type="button" className="text-link" onClick={()=>setPhotos([])}>Remover fotos</button>}<p className="muted">As fotos só serão enviadas depois da confirmação final. Você pode continuar sem elas.</p></>}
{step===6&&<><label className="field">Região ou cidade<input required maxLength={100} value={data.region} onChange={e=>update("region",e.target.value)} aria-describedby="check-error" aria-invalid={!!error}/></label><label className="field">CEP (opcional)<input inputMode="numeric" autoComplete="postal-code" maxLength={9} value={data.cep} onChange={e=>update("cep",e.target.value.replace(/\D/g,"").slice(0,8))}/></label></>}
{step===7&&<><div className="field-grid"><label className="field">Nome<input required autoComplete="name" maxLength={100} value={data.name} onChange={e=>update("name",e.target.value)} aria-describedby="check-error"/></label><label className="field">Telefone com DDD<input required type="tel" autoComplete="tel-national" maxLength={16} value={data.phone} onChange={e=>update("phone",e.target.value.replace(/\D/g,"").slice(0,11))} aria-describedby="check-error"/></label></div><label className="field">Email (opcional)<input type="email" autoComplete="email" maxLength={150} value={data.email} onChange={e=>update("email",e.target.value)}/></label><label className="field">Algo mais que devemos saber? (opcional)<textarea maxLength={1200} rows={3} value={data.notes} onChange={e=>update("notes",e.target.value)}/></label><div className="honeypot" aria-hidden="true"><label>Website<input tabIndex={-1} autoComplete="off" value={data.website} onChange={e=>update("website",e.target.value)}/></label></div><details className="review-summary" open><summary>Revisar respostas</summary><dl>{[["Problema",problems.find(([p])=>p===data.problem)?.[1]],["Local",data.location],["Imóvel",{residencia:"Residência",condominio:"Condomínio",empresa:"Empresa"}[data.property]],["Urgência",{agora:"Afeta o funcionamento agora",planejar:"Planejar atendimento","nao-sei":"Ainda não sei"}[data.urgency]],["Acesso",data.access],["Região",data.region],["CEP",data.cep||"Não informado"],["Fotos",String(photos.length)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><button type="button" className="text-link" onClick={()=>go(0)}>Editar respostas</button></details><label className="check-label"><Checkbox checked={privacy} onCheckedChange={v=>setPrivacy(v===true)}/><span>Li o <a href="/privacidade" target="_blank" rel="noreferrer">aviso de privacidade</a> e estou ciente do uso dos dados para esta solicitação.</span></label><label className="check-label"><Checkbox checked={data.marketing} onCheckedChange={v=>update("marketing",v===true)}/><span>Quero receber comunicações de manutenção e novidades. Opcional; posso revogar depois.</span></label>{mode==="review"&&<label className="check-label"><Checkbox checked={data.reviewAcknowledged} onCheckedChange={v=>update("reviewAcknowledged",v===true)}/><span>Estou usando dados fictícios para revisar este fluxo.</span></label>}</>}
</div><p id="check-error" role="alert" className="form-error">{error}</p><div className="check-nav">{step>0?<button type="button" className="outline-button" disabled={busy} onClick={()=>go(step-1)}>← Voltar</button>:<a className="text-link" href="/">Voltar ao site</a>}<button className="button" type="submit" disabled={busy||(step===7&&mode==="disabled")}>{busy?"Registrando…":step===7?(mode==="review"?"Registrar teste ↗":"Enviar solicitação ↗"):"Continuar →"}</button></div></form>}<noscript>Ative o JavaScript para preencher o Limpax Check.</noscript></div>}



