"use client";

import {useState,type FormEvent} from "react";
import Link from "next/link";
import {defaultLinkSelection,loadLinkableCustomer,removeLeadCustomerLink,saveLeadCustomerLink,searchLinkableCustomers,type LeadCustomerSelection,type LinkableCustomer,type LinkableCustomerDetail} from "@/lib/crm-customer-link";

export type LinkedCustomer={customerId:string;customerName:string;customerKind:string;contactId:string|null;locationId:string|null;linkedAt:number;linkedBy:string};

export function LeadCustomerLinker({leadId,leadMode="review",linkedCustomer,onChanged}:{leadId:string;leadMode?:"review"|"live";linkedCustomer:LinkedCustomer|null;onChanged:()=>void|Promise<void>}){
  const [query,setQuery]=useState(""),[results,setResults]=useState<LinkableCustomer[]>([]),[detail,setDetail]=useState<LinkableCustomerDetail|null>(null),[selection,setSelection]=useState<LeadCustomerSelection|null>(null),[searched,setSearched]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");

  async function search(event:FormEvent){event.preventDefault();const value=query.trim();if(!value)return;setBusy(true);setError("");setSearched(false);setDetail(null);setSelection(null);try{setResults(await searchLinkableCustomers(fetch,value,leadMode));setSearched(true)}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function choose(customer:LinkableCustomer){setBusy(true);setError("");try{const value=await loadLinkableCustomer(fetch,customer.id);setDetail(value);setSelection(defaultLinkSelection(value))}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function link(){if(!selection)return;setBusy(true);setError("");try{await saveLeadCustomerLink(fetch,leadId,selection);await onChanged()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function unlink(){setBusy(true);setError("");try{await removeLeadCustomerLink(fetch,leadId);await onChanged()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}

  if(linkedCustomer)return <section className="crm-customer-link" aria-labelledby="linked-customer-title"><div><span className="eyebrow" id="linked-customer-title">CLIENTE VINCULADO</span><strong>{linkedCustomer.customerName}</strong><small>Cadastro associado a este atendimento.</small></div><div className="crm-customer-link-actions"><Link className="outline-button" href="/crm/clientes">Abrir clientes</Link><button type="button" className="crm-text-button" disabled={busy} onClick={()=>void unlink()}>{busy?"Removendo…":"Desvincular"}</button></div>{error&&<p className="crm-link-error" role="alert">{error}</p>}</section>;

  return <section className="crm-customer-link" aria-labelledby="customer-link-title"><div className="crm-customer-link-head"><div><span className="eyebrow" id="customer-link-title">CADASTRO DO CLIENTE</span><strong>Vincular atendimento</strong><small>Associe este pedido a um cliente já cadastrado.</small></div></div><form className="crm-customer-search" onSubmit={search}><label htmlFor={`customer-search-${leadId}`}>Buscar cliente</label><div><input id={`customer-search-${leadId}`} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Nome, empresa, CPF ou CNPJ" minLength={2} maxLength={120} required/><button className="outline-button" disabled={busy}>{busy?"Buscando…":"Buscar"}</button></div></form>{error&&<p className="crm-link-error" role="alert">{error}</p>}{searched&&!results.length&&<p className="crm-link-empty">Nenhum cliente encontrado.</p>}{!!results.length&&<ul className="crm-customer-results" aria-label="Clientes encontrados">{results.map(customer=><li key={customer.id}><button type="button" aria-pressed={detail?.id===customer.id} disabled={busy} onClick={()=>void choose(customer)}><strong>{customer.tradeName||customer.name}</strong>{customer.tradeName&&<small>{customer.name}</small>}</button></li>)}</ul>}{detail&&selection&&<div className="crm-link-selection"><p><strong>{detail.tradeName||detail.name}</strong><span>{detail.kind==="organization"?"Empresa":"Pessoa"}</span></p><label>Contato<select value={selection.contactId||""} onChange={event=>setSelection(current=>current?{...current,contactId:event.target.value||undefined}:current)}><option value="">Sem contato específico</option>{detail.contactList.map(contact=><option key={contact.id} value={contact.id}>{contact.name}{contact.phone?" · "+contact.phone:""}</option>)}</select></label><label>Local de serviço<select value={selection.locationId||""} onChange={event=>setSelection(current=>current?{...current,locationId:event.target.value||undefined}:current)}><option value="">Sem local específico</option>{detail.locationList.map(location=><option key={location.id} value={location.id}>{location.label}{location.city?" · "+location.city:""}</option>)}</select></label><button type="button" className="button" disabled={busy} onClick={()=>void link()}>{busy?"Vinculando…":"Vincular atendimento"}</button></div>}</section>;
}
