import {requireCrmUser,requireCrmMutation,toDateTime} from "@/lib/crm";
import {crmStatuses} from "@/lib/crm-shared";
import {database,json,failure,readJson,ApiError} from "@/lib/http";
import {settings} from "@/lib/config";
import {uuidSchema} from "@/lib/validation";
import {z} from "zod";
import {mapCrmLead,readLeadPayload} from "@/lib/crm-data";
type LeadRow={seq:number;id:string;payload:string;status:string;mode:string;created_at:number;updated_at:number;assigned_to:string|null;next_action_at:number|null;privacy_version:string;marketing:number};
type LinkRow={customer_id:string;contact_id:string|null;location_id:string|null;linked_at:number;linked_by:string;customer_name:string;trade_name:string|null;kind:string};
type ExistingLead={id:string;status:string;assigned_to:string|null;next_action_at:number|null};
const updateSchema=z.object({status:z.enum(crmStatuses).optional(),assignedTo:z.string().trim().max(150).nullable().optional(),nextActionAt:z.string().optional()}).strict();
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{await requireCrmUser();const {id}=await params;if(!uuidSchema.safeParse(id).success)throw new ApiError(400,"Identificador inválido.");const db=database(settings());const row=await db.prepare("SELECT seq,id,payload,status,mode,created_at,updated_at,assigned_to,next_action_at,privacy_version,marketing FROM leads WHERE id=?").bind(id).first<LeadRow>();if(!row)throw new ApiError(404,"Solicitação não encontrada.");const [activities,tasks,attachments,link]=await Promise.all([db.prepare("SELECT id,kind,body,author,created_at FROM lead_activities WHERE lead_id=? ORDER BY created_at DESC LIMIT 100").bind(id).all(),db.prepare("SELECT id,title,due_at,assignee,completed_at,created_at FROM crm_tasks WHERE lead_id=? ORDER BY completed_at IS NOT NULL,due_at ASC,created_at DESC LIMIT 100").bind(id).all(),db.prepare("SELECT id,mime,bytes,created_at FROM attachments WHERE lead_id=? ORDER BY created_at DESC").bind(id).all(),db.prepare("SELECT lc.customer_id,lc.contact_id,lc.location_id,lc.linked_at,lc.linked_by,c.name AS customer_name,c.trade_name,c.kind FROM lead_customer_links lc JOIN customers c ON c.id=lc.customer_id WHERE lc.lead_id=?").bind(id).first<LinkRow>()]);const linkedCustomer=link?{customerId:link.customer_id,customerName:link.trade_name||link.customer_name,customerKind:link.kind,contactId:link.contact_id,locationId:link.location_id,linkedAt:Number(link.linked_at),linkedBy:link.linked_by}:null;return json({lead:{...mapCrmLead(row),payload:readLeadPayload(row.payload),privacyVersion:row.privacy_version,marketing:Number(row.marketing)},activities:activities.results,tasks:tasks.results,attachments:attachments.results,linkedCustomer})}catch(e){return failure(e)}}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireCrmMutation(req);const {id}=await params;if(!uuidSchema.safeParse(id).success)throw new ApiError(400,"Identificador inválido.");const parsed=updateSchema.safeParse(await readJson(req));if(!parsed.success||!Object.keys(parsed.data).length)throw new ApiError(400,"Atualização inválida.");const data=parsed.data;const next=data.nextActionAt===undefined?undefined:toDateTime(data.nextActionAt);const db=database(settings());const existing=await db.prepare("SELECT id,status,assigned_to,next_action_at FROM leads WHERE id=?").bind(id).first<ExistingLead>();if(!existing)throw new ApiError(404,"Solicitação não encontrada.");const status=data.status??existing.status,assigned=data.assignedTo===undefined?existing.assigned_to:data.assignedTo,nextAction=data.nextActionAt===undefined?existing.next_action_at:next,now=Date.now();await db.batch([db.prepare("UPDATE leads SET status=?,assigned_to=?,next_action_at=?,updated_at=? WHERE id=?").bind(status,assigned,nextAction,now,id),db.prepare("INSERT INTO lead_activities (id,lead_id,kind,body,author,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),id,"update",activityMessage(existing,{status,assignedTo:assigned,nextActionAt:nextAction}),user.email,now)]);return json({id,status,assignedTo:assigned,nextActionAt:nextAction,updatedAt:now})}catch(e){return failure(e)}}
function activityMessage(before:ExistingLead,after:{status:string;assignedTo:string|null|undefined;nextActionAt:number|null|undefined}){const changes:string[]=[];if(before.status!==after.status)changes.push("Status: "+after.status);if(before.assigned_to!==after.assignedTo)changes.push("Responsável atualizado");if(before.next_action_at!==after.nextActionAt)changes.push("Próxima ação atualizada");return changes.join(" · ")||"Registro atualizado"}
