import {requireCrmUser,requireCrmMutation,toDateTime} from "@/lib/crm";
import {crmStatuses} from "@/lib/crm-shared";
import {database,json,failure,readJson,ApiError} from "@/lib/http";
import {settings} from "@/lib/config";
import {uuidSchema} from "@/lib/validation";
import {z} from "zod";
import {mapCrmLead,readLeadPayload} from "@/lib/crm-data";
const updateSchema=z.object({status:z.enum(crmStatuses).optional(),assignedTo:z.string().trim().max(150).nullable().optional(),nextActionAt:z.string().optional()}).strict();
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{await requireCrmUser();const {id}=await params;if(!uuidSchema.safeParse(id).success)throw new ApiError(400,"Identificador inválido.");const db=database(settings());const row=await db.prepare("SELECT seq,id,payload,status,mode,created_at,updated_at,assigned_to,next_action_at,privacy_version,marketing FROM leads WHERE id=?").bind(id).first<any>();if(!row)throw new ApiError(404,"Solicitação não encontrada.");const [activities,tasks,attachments]=await Promise.all([db.prepare("SELECT id,kind,body,author,created_at FROM lead_activities WHERE lead_id=? ORDER BY created_at DESC LIMIT 100").bind(id).all(),db.prepare("SELECT id,title,due_at,assignee,completed_at,created_at FROM crm_tasks WHERE lead_id=? ORDER BY completed_at IS NOT NULL,due_at ASC,created_at DESC LIMIT 100").bind(id).all(),db.prepare("SELECT id,mime,bytes,created_at FROM attachments WHERE lead_id=? ORDER BY created_at DESC").bind(id).all()]);return json({lead:{...mapCrmLead(row),payload:readLeadPayload(row.payload),privacyVersion:row.privacy_version,marketing:Number(row.marketing)},activities:activities.results,tasks:tasks.results,attachments:attachments.results})}catch(e){return failure(e)}}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireCrmMutation(req);const {id}=await params;if(!uuidSchema.safeParse(id).success)throw new ApiError(400,"Identificador inválido.");const parsed=updateSchema.safeParse(await readJson(req));if(!parsed.success||!Object.keys(parsed.data).length)throw new ApiError(400,"Atualização inválida.");const data=parsed.data;const next=data.nextActionAt===undefined?undefined:toDateTime(data.nextActionAt);const db=database(settings());const existing=await db.prepare("SELECT id,status,assigned_to,next_action_at FROM leads WHERE id=?").bind(id).first<any>();if(!existing)throw new ApiError(404,"Solicitação não encontrada.");const status=data.status??existing.status,assigned=data.assignedTo===undefined?existing.assigned_to:data.assignedTo,nextAction=data.nextActionAt===undefined?existing.next_action_at:next,now=Date.now();await db.batch([db.prepare("UPDATE leads SET status=?,assigned_to=?,next_action_at=?,updated_at=? WHERE id=?").bind(status,assigned,nextAction,now,id),db.prepare("INSERT INTO lead_activities (id,lead_id,kind,body,author,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),id,"update",activityMessage(existing,{status,assignedTo:assigned,nextActionAt:nextAction}),user.email,now)]);return json({id,status,assignedTo:assigned,nextActionAt:nextAction,updatedAt:now})}catch(e){return failure(e)}}
function activityMessage(before:any,after:any){const changes=[];if(before.status!==after.status)changes.push("Status: "+after.status);if(before.assigned_to!==after.assignedTo)changes.push("Responsável atualizado");if(before.next_action_at!==after.nextActionAt)changes.push("Próxima ação atualizada");return changes.join(" · ")||"Registro atualizado"}
