import type {Settings} from "./config";
export class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}})}
export async function boundedBody(req:Request,max:number){const length=Number(req.headers.get("content-length"));if(length>max)throw new ApiError(413,"Arquivo ou solicitação acima do limite.");const reader=req.body?.getReader();if(!reader)return new Uint8Array();const chunks:Uint8Array[]=[];let size=0;try{for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new ApiError(413,"Arquivo ou solicitação acima do limite.")}chunks.push(value)}}finally{reader.releaseLock()}const result=new Uint8Array(size);let offset=0;for(const c of chunks){result.set(c,offset);offset+=c.length}return result}
export async function readJson(req:Request){if(!req.headers.get("content-type")?.startsWith("application/json"))throw new ApiError(415,"Formato de solicitação inválido.");try{return JSON.parse(new TextDecoder().decode(await boundedBody(req,12000)))}catch(e){if(e instanceof ApiError)throw e;throw new ApiError(400,"Solicitação inválida.")}}
export function requireOrigin(req:Request,s:Settings){const url=new URL(req.url);const allowed=s.SITE_ORIGIN||"https://limpax-fluindo.italopablo.chatgpt.site";const local=["localhost","127.0.0.1"].includes(url.hostname);if(req.headers.get("origin")!==(local?url.origin:allowed))throw new ApiError(403,"Origem não autorizada.")}
export async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(v=>v.toString(16).padStart(2,"0")).join("")}
export async function authorize(req:Request,s:Settings){const token=s.CRM_API_TOKEN;if(!token||token.length<32)throw new ApiError(503,"Integração não configurada.");const actual=req.headers.get("authorization")||"";const a=await digest(actual),b=await digest("Bearer "+token);let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);if(d!==0)throw new ApiError(401,"Não autorizado.")}
export function database(s:Settings){if(!s.DB)throw new ApiError(503,"Registro temporariamente indisponível.");return s.DB}
export async function rateLimit(req:Request,s:Settings,scope:string,limit=10){const db=database(s);const window=Math.floor(Date.now()/600000);const ip=req.headers.get("cf-connecting-ip")||"local";const key=await digest((s.RATE_LIMIT_SECRET||"private-review")+"|"+ip+"|"+window+"|"+scope);const row=await db.prepare("INSERT INTO rate_limits (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count").bind(key,(window+1)*600000).first<{count:number}>();if(!row||row.count>limit)throw new ApiError(429,"Muitas tentativas. Aguarde alguns minutos.")}
export function failure(error:unknown){if(error instanceof ApiError)return json({error:error.message},error.status);console.error("Limpax API failure",error instanceof Error?error.name:"Unknown");return json({error:"Não foi possível concluir. Tente novamente."},503)}

