import {leadSchema,idempotencySchema} from "./validation";
import {ApiError,database,digest} from "./http";
import {captureMode,type Settings} from "./config";
export async function createLead(input:unknown,key:string|null,s:Settings){const parsed=leadSchema.safeParse(input);if(!parsed.success||!idempotencySchema.safeParse(key).success)throw new ApiError(400,"Revise os campos obrigatórios e tente novamente.");const mode=captureMode(s);if(mode==="disabled")throw new ApiError(503,"O recebimento está temporariamente indisponível.");if(mode==="review"&&!parsed.data.reviewAcknowledged)throw new ApiError(400,"Confirme o uso de dados fictícios neste ambiente de revisão.");
const db=database(s);const payload=JSON.stringify(parsed.data);const hash=await digest(payload);const old=await db.prepare("SELECT id,payload_hash,mode FROM leads WHERE idempotency=?").bind(key).first<{id:string;payload_hash:string;mode:string}>();if(old){if(old.payload_hash!==hash)throw new ApiError(409,"A solicitação mudou. Inicie um novo envio.");return {id:old.id,mode:old.mode,replayed:true}}
const id=crypto.randomUUID(),uploadToken=crypto.randomUUID()+crypto.randomUUID(),now=Date.now();try{await db.batch([db.prepare("INSERT INTO leads (id,idempotency,payload_hash,payload,mode,status,created_at,privacy_version,marketing,upload_hash,upload_expires,upload_count) VALUES (?,?,?,?,?,'novo',?,'2026-09-15',?,?,?,0)").bind(id,key,hash,payload,mode,now,Number(parsed.data.marketing),await digest(uploadToken),now+900000),db.prepare("INSERT INTO outbox (lead_id,state,attempts,next_attempt,lease_until) VALUES (?,?,0,0,0)").bind(id,mode==="live"?"pending":"review")])}catch(e){const same=await db.prepare("SELECT id,payload_hash,mode FROM leads WHERE idempotency=?").bind(key).first<{id:string;payload_hash:string;mode:string}>();if(same&&same.payload_hash===hash)return {id:same.id,mode:same.mode,replayed:true};if(same)throw new ApiError(409,"A solicitação mudou. Inicie um novo envio.");throw e}
return {id,mode,uploadToken,replayed:false};
}

