import {sqliteTable,text,integer,index,uniqueIndex} from "drizzle-orm/sqlite-core";
export const leads=sqliteTable("leads",{
seq:integer("seq").primaryKey({autoIncrement:true}),id:text("id").notNull().unique(),idempotency:text("idempotency").notNull().unique(),payloadHash:text("payload_hash").notNull(),payload:text("payload").notNull(),mode:text("mode").notNull(),status:text("status").notNull().default("novo"),createdAt:integer("created_at").notNull(),privacyVersion:text("privacy_version").notNull(),marketing:integer("marketing").notNull(),uploadHash:text("upload_hash").notNull(),uploadExpires:integer("upload_expires").notNull(),uploadCount:integer("upload_count").notNull().default(0)
},t=>[index("idx_leads_created").on(t.createdAt)]);
export const outbox=sqliteTable("outbox",{leadId:text("lead_id").primaryKey().references(()=>leads.id,{onDelete:"cascade"}),state:text("state").notNull().default("pending"),attempts:integer("attempts").notNull().default(0),nextAttempt:integer("next_attempt").notNull().default(0),leaseUntil:integer("lease_until").notNull().default(0),deliveredAt:integer("delivered_at"),lastError:text("last_error")},t=>[index("idx_outbox_pending").on(t.state,t.nextAttempt)]);
export const attachments=sqliteTable("attachments",{id:text("id").primaryKey(),leadId:text("lead_id").notNull().references(()=>leads.id,{onDelete:"cascade"}),objectKey:text("object_key").notNull(),mime:text("mime").notNull(),bytes:integer("bytes").notNull(),createdAt:integer("created_at").notNull()},t=>[index("idx_attachments_lead").on(t.leadId)]);
export const rates=sqliteTable("rate_limits",{key:text("key").primaryKey(),count:integer("count").notNull(),expires:integer("expires").notNull()},t=>[index("idx_rates_expires").on(t.expires)]);
export const events=sqliteTable("events",{day:text("day").notNull(),event:text("event").notNull(),count:integer("count").notNull()},t=>[uniqueIndex("idx_events_day_event").on(t.day,t.event)]);
export const serviceRecords=sqliteTable("service_records",{id:text("id").primaryKey(),leadId:text("lead_id").references(()=>leads.id,{onDelete:"set null"}),completedAt:integer("completed_at"),category:text("category"),vehicleId:text("vehicle_id"),nextReview:integer("next_review"),intervalDays:integer("interval_days")});

