import {sqliteTable,text,integer,index,uniqueIndex} from "drizzle-orm/sqlite-core";
export const leads=sqliteTable("leads",{
seq:integer("seq").primaryKey({autoIncrement:true}),id:text("id").notNull().unique(),idempotency:text("idempotency").notNull().unique(),payloadHash:text("payload_hash").notNull(),payload:text("payload").notNull(),mode:text("mode").notNull(),origin:text("origin").notNull().default("unknown"),importBatch:text("import_batch"),status:text("status").notNull().default("novo"),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at"),assignedTo:text("assigned_to"),nextActionAt:integer("next_action_at"),privacyVersion:text("privacy_version").notNull(),marketing:integer("marketing").notNull(),uploadHash:text("upload_hash").notNull(),uploadExpires:integer("upload_expires").notNull(),uploadCount:integer("upload_count").notNull().default(0)
},t=>[index("idx_leads_created").on(t.createdAt),index("idx_leads_status_updated").on(t.status,t.updatedAt),index("idx_leads_mode_origin").on(t.mode,t.origin)]);
export const outbox=sqliteTable("outbox",{leadId:text("lead_id").primaryKey().references(()=>leads.id,{onDelete:"cascade"}),state:text("state").notNull().default("pending"),attempts:integer("attempts").notNull().default(0),nextAttempt:integer("next_attempt").notNull().default(0),leaseUntil:integer("lease_until").notNull().default(0),deliveredAt:integer("delivered_at"),lastError:text("last_error")},t=>[index("idx_outbox_pending").on(t.state,t.nextAttempt)]);
export const attachments=sqliteTable("attachments",{id:text("id").primaryKey(),leadId:text("lead_id").notNull().references(()=>leads.id,{onDelete:"cascade"}),objectKey:text("object_key").notNull(),mime:text("mime").notNull(),bytes:integer("bytes").notNull(),createdAt:integer("created_at").notNull()},t=>[index("idx_attachments_lead").on(t.leadId)]);
export const rates=sqliteTable("rate_limits",{key:text("key").primaryKey(),count:integer("count").notNull(),expires:integer("expires").notNull()},t=>[index("idx_rates_expires").on(t.expires)]);
export const events=sqliteTable("events",{day:text("day").notNull(),event:text("event").notNull(),count:integer("count").notNull()},t=>[uniqueIndex("idx_events_day_event").on(t.day,t.event)]);
export const serviceRecords=sqliteTable("service_records",{id:text("id").primaryKey(),leadId:text("lead_id").references(()=>leads.id,{onDelete:"set null"}),completedAt:integer("completed_at"),category:text("category"),vehicleId:text("vehicle_id"),nextReview:integer("next_review"),intervalDays:integer("interval_days")});
export const leadActivities=sqliteTable("lead_activities",{id:text("id").primaryKey(),leadId:text("lead_id").notNull().references(()=>leads.id,{onDelete:"cascade"}),kind:text("kind").notNull(),body:text("body").notNull(),author:text("author").notNull(),createdAt:integer("created_at").notNull()},t=>[index("idx_activities_lead").on(t.leadId,t.createdAt)]);
export const crmTasks=sqliteTable("crm_tasks",{id:text("id").primaryKey(),leadId:text("lead_id").notNull().references(()=>leads.id,{onDelete:"cascade"}),title:text("title").notNull(),dueAt:integer("due_at"),assignee:text("assignee"),completedAt:integer("completed_at"),createdAt:integer("created_at").notNull(),idempotencyKey:text("idempotency_key"),requestHash:text("request_hash")},t=>[index("idx_tasks_lead").on(t.leadId,t.completedAt),uniqueIndex("idx_tasks_idempotency").on(t.leadId,t.idempotencyKey)]);
export const crmUserProfiles=sqliteTable("crm_user_profiles",{email:text("email").primaryKey(),displayName:text("display_name"),role:text("role").notNull(),active:integer("active").notNull().default(1),lastSeenAt:integer("last_seen_at"),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()},t=>[index("idx_crm_users_role_active").on(t.role,t.active)]);
export const customers=sqliteTable("customers",{id:text("id").primaryKey(),kind:text("kind").notNull(),name:text("name").notNull(),tradeName:text("trade_name"),taxId:text("tax_id"),taxIdNormalized:text("tax_id_normalized"),notes:text("notes"),sourceMode:text("source_mode").notNull().default("review"),origin:text("origin").notNull().default("unknown"),importBatch:text("import_batch"),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull(),archivedAt:integer("archived_at")},t=>[index("idx_customers_name").on(t.name),index("idx_customers_source_mode").on(t.sourceMode),uniqueIndex("idx_customers_tax_id").on(t.taxIdNormalized)]);
export const customerContacts=sqliteTable("customer_contacts",{id:text("id").primaryKey(),customerId:text("customer_id").notNull().references(()=>customers.id,{onDelete:"cascade"}),name:text("name").notNull(),role:text("role"),phone:text("phone"),phoneNormalized:text("phone_normalized"),email:text("email"),primary:integer("is_primary").notNull().default(0),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()},t=>[index("idx_contacts_customer").on(t.customerId),index("idx_contacts_phone").on(t.phoneNormalized),index("idx_contacts_email").on(t.email)]);
export const serviceLocations=sqliteTable("service_locations",{id:text("id").primaryKey(),customerId:text("customer_id").notNull().references(()=>customers.id,{onDelete:"cascade"}),label:text("label").notNull(),postalCode:text("postal_code"),address:text("address"),number:text("number"),complement:text("complement"),district:text("district"),city:text("city"),state:text("state"),reference:text("reference"),accessNotes:text("access_notes"),primary:integer("is_primary").notNull().default(0),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()},t=>[index("idx_locations_customer").on(t.customerId)]);
export const leadCustomerLinks=sqliteTable("lead_customer_links",{leadId:text("lead_id").primaryKey().references(()=>leads.id,{onDelete:"cascade"}),customerId:text("customer_id").notNull().references(()=>customers.id,{onDelete:"cascade"}),contactId:text("contact_id").references(()=>customerContacts.id,{onDelete:"set null"}),locationId:text("location_id").references(()=>serviceLocations.id,{onDelete:"set null"}),linkedAt:integer("linked_at").notNull(),linkedBy:text("linked_by").notNull()},t=>[index("idx_lead_customer_customer").on(t.customerId)]);
export const crmAuditLog=sqliteTable("crm_audit_log",{id:text("id").primaryKey(),entityType:text("entity_type").notNull(),entityId:text("entity_id").notNull(),action:text("action").notNull(),author:text("author").notNull(),data:text("data"),createdAt:integer("created_at").notNull()},t=>[index("idx_audit_entity").on(t.entityType,t.entityId,t.createdAt),index("idx_audit_author").on(t.author,t.createdAt)]);
